language: java

jdk:
- oraclejdk8

# Build everything in 'script' phase
install: /bin/true

script: "git log --format=%s HEAD~1..HEAD | grep -q 'fixes #' && mvn integration || mvn install"

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master

