language: java

jdk:
- oraclejdk8

# Build everything in 'script' phase
install: /bin/true

script:
  - mvn clean install

after_failure:
  - cat target/surefire-reports/*.txt

after_success:
  - cat target/surefire-reports/*.txt

notifications:
  email:
    recipients:
      - alex.bretet@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master

