language: java

jdk:
- oraclejdk8

# Build everything in 'script' phase
install: /bin/true

script:
  - mvn clean install cobertura:cobertura

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

after_failure:
  - cat target/surefire-reports/*.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9d148108-d308-4881-8d64-0124ec90814d

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master

