codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "40...100"
  status:
    project:
      default:
        target: auto
        threshold: 0
        branches:
          - .*
    patch:
      default:
        target: auto
        branches:
          - .*
    changes:
      default:
        target: auto
        branches:
          - .*